#!/bin/bash

sbatch cluster_scripts/multiphase_scripts/ehe/C.35620/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.33100/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.31080/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.12060/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.26420/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.19100/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.16980/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.47900/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.37980/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.36740/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.41860/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.38060/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.45300/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.40140/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.19820/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.12580/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.29820/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.14460/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.41740/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.16740/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.41700/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.27260/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.35380/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.32820/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.42660/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.12420/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.26900/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.17140/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.18140/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.12940/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.40900/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.17460/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
sbatch cluster_scripts/multiphase_scripts/ehe/C.41180/multiphase_pop.ehe__trans.ehe__full.ehe1.bat
