pop.lik = population.likelihood.instructions$instantiate.likelihood('ehe','C.12580')
imm.lik = immigration.likelihood.instructions$instantiate.likelihood('ehe','C.12580')
em.lik = emigration.likelihood.instructions$instantiate.likelihood('ehe','C.12580')
new.lik = new.diagnoses.likelihood.instructions$instantiate.likelihood('ehe','C.12580')
prev.lik = prevalence.likelihood.instructions$instantiate.likelihood('ehe','C.12580')

new.lik.two.way = race.risk.sex.two.way.new.diagnoses.likelihood.instructions$instantiate.likelihood('ehe','C.12580')
prev.lik.two.way = race.risk.sex.two.way.prevalence.likelihood.instructions$instantiate.likelihood('ehe','C.12580')

hiv.mort.lik = hiv.mortality.likelihood.instructions$instantiate.likelihood('ehe','C.12580')
gen.mort.lik = general.mortality.likelihood.instructions$instantiate.likelihood('ehe','C.12580')
aids.deaths.lik = aids.deaths.likelihood.instructions$instantiate.likelihood('ehe','C.12580')
aids.diag.lik = aids.diagnoses.likelihood.instructions$instantiate.likelihood('ehe','C.12580')
prop.tested.lik = proportion.tested.likelihood.instructions$instantiate.likelihood('ehe','C.12580')
positivity.lik = hiv.test.positivity.likelihood.instructions$instantiate.likelihood('ehe','C.12580')
aware.lik = awareness.likelihood.instructions$instantiate.likelihood('ehe','C.12580')
supp.lik = suppression.likelihood.instructions$instantiate.likelihood('ehe','C.12580')
prep.uptake.lik = prep.uptake.likelihood.instructions$instantiate.likelihood('ehe','C.12580')
prep.ind.lik = prep.indications.likelihood.instructions$instantiate.likelihood('ehe','C.12580')
heroin.lik = heroin.likelihood.instructions$instantiate.likelihood('ehe','C.12580')
cocaine.lik = cocaine.likelihood.instructions$instantiate.likelihood('ehe','C.12580')


exp(pop.lik$compute.piecewise(sim.full) - pop.lik$compute.piecewise(sim.old))
exp(imm.lik$compute.piecewise(sim.full) - imm.lik$compute.piecewise(sim.old))
exp(em.lik$compute.piecewise(sim.full) - em.lik$compute.piecewise(sim.old))
exp(new.lik$compute.piecewise(sim.full) - new.lik$compute.piecewise(sim.old))
exp(prev.lik$compute.piecewise(sim.full) - prev.lik$compute.piecewise(sim.old))
exp(hiv.mort.lik$compute.piecewise(sim.full) - hiv.mort.lik$compute.piecewise(sim.old))
exp(gen.mort.lik$compute.piecewise(sim.full) - gen.mort.lik$compute.piecewise(sim.old))
exp(aids.deaths.lik$compute.piecewise(sim.full) - aids.deaths.lik$compute.piecewise(sim.old))
exp(aids.diag.lik$compute.piecewise(sim.full) - aids.diag.lik$compute.piecewise(sim.old))
exp(prop.tested.lik$compute.piecewise(sim.full) - prop.tested.lik$compute.piecewise(sim.old))
exp(positivity.lik$compute.piecewise(sim.full) - positivity.lik$compute.piecewise(sim.old))
exp(aware.lik$compute.piecewise(sim.full) - aware.lik$compute.piecewise(sim.old))
exp(supp.lik$compute.piecewise(sim.full) - supp.lik$compute.piecewise(sim.old))
exp(prep.uptake.lik$compute.piecewise(sim.full) - prep.uptake.lik$compute.piecewise(sim.old))
exp(prep.ind.lik$compute.piecewise(sim.full) - prep.ind.lik$compute.piecewise(sim.old))
exp(heroin.lik$compute.piecewise(sim.full) - heroin.lik$compute.piecewise(sim.old))
exp(cocaine.lik$compute.piecewise(sim.full) - cocaine.lik$compute.piecewise(sim.old))


prop.tested.lik.old$compute.piecewise(sim.full) - prop.tested.lik.old$compute.piecewise(sim.old)
prop.test.lik.new$compute.piecewise(sim.full) - prop.test.lik.new$compute.piecewise(sim.old)

aware.lik.old$compute.piecewise(sim.full) - aware.lik.old$compute.piecewise(sim.old)
