# CITIES/LIKELIHOODS THAT NEED NEW IFELSE METHOD

# AWARENESS: RIVERSIDE, MIAMI, LA, VEGAS, SAN DIEGO
# SUPPRESSION: RIVERSIDE, MIAMI, LA, VEGAS
# HEROIN: LA, VEGAS, SAN DIEGO
# COCAINE: LA, VEGAS, SAN DIEGO

# RIVERSIDE: AWARENESS & SUPPRESSION - done
# LA: HEROIN & COCAINE; AWARENESS; SUPPRESSION - done
# MIAMI: AWARENESS & SUPPRESSION - done
# VEGAS: HEROIN & COCAINE; AWARENESS; SUPPRESSION - done
# SAN DIEGO: HEROIN & COCAINE; AWARENESS - done


