# CITIES/LIKELIHOODS THAT NEED NEW IFELSE METHOD

# AWARENESS: RIVERSIDE, MIAMI
# SUPPRESSION: RIVERSIDE
# HEROIN: LA, VEGAS, SAN DIEGO
# COCAINE: LA, VEGAS, SAN DIEGO

# RIVERSIDE: AWARENESS & SUPPRESSION - done
# LA: HEROIN & COCAINE - done
# MIAMI: AWARENESS - done
# VEGAS: HEROIN & COCAINE - done
# SAN DIEGO: HEROIN & COCAINE - done


