register.ontology.mapping('lump.other.risk.and.heterosexual',
                          from.dimensions = 'risk',
                          to.dimensions = 'risk',
                          mappings = rbind(c('msm', 'msm'),
                                           c('idu', 'idu'),
                                           c('msm_idu', 'msm_idu'),
                                           c('heterosexual', 'heterosexual'),
                                           c('other', 'heterosexual'))
)

register.ontology.mapping('jheem.to.cdc.sex.risk',
                          from.dimensions = c('sex', 'risk'),
                          to.dimensions = c('sex', 'risk'),
                          mappings = rbind(c('msm', 'never_IDU', 'male', 'msm'),
                                           c('msm', 'active_IDU', 'male', 'msm_idu'),
                                           c('msm', 'IDU_in_remission', 'male', 'msm_idu'),
                                           c('heterosexual_male', 'never_IDU', 'male', 'heterosexual'),
                                           c('heterosexual_male', 'active_IDU', 'male', 'idu'),
                                           c('heterosexual_male', 'IDU_in_remission', 'male', 'idu'),
                                           c('female', 'never_IDU', 'female', 'heterosexual'),
                                           c('female', 'active_IDU', 'female', 'idu'),
                                           c('female', 'IDU_in_remission', 'female', 'idu'))
)

register.ontology.mapping('cdc.to.jheem.race',
                          from.dimensions = 'race',
                          to.dimensions = 'race',
                          mappings = rbind(c('American Indian/Alaska Native', 'other'),
                                           c('Asian', 'other'),
                                           c('Black/African American', 'black'),
                                           c('Hispanic/Latino', 'hispanic'),
                                           c('Multiracial', 'other'),
                                           c('Native Hawaiian/Other Pacific Islander', 'other'),
                                           c('White', 'other'))
)

register.ontology.mapping('cdc.msa.reports.to.jheem.race',
                          from.dimensions = 'race',
                          to.dimensions = 'race',
                          mappings = rbind(c('American Indian/Alaska Native', 'other'),
                                           c('Asian', 'other'),
                                           c('Black/African American', 'black'),
                                           c('Hispanic/Latino', 'hispanic'),
                                           c('White', 'other')))
register.ontology.mapping('wonder.to.census.race.1',
                          from.dimensions = 'race',
                          to.dimensions = 'race',
                          mappings = rbind(c('American Indian or Alaska Native', 'american indian or alaska native'),
                                           c('Asian or Pacific Islander', 'asian or pacific islander'),
                                           c('Black or African American', 'black'),
                                           c('White', 'white')))
register.ontology.mapping('wonder.to.census.race.2',
                          from.dimensions = 'race',
                          to.dimensions = 'race',
                          mappings = rbind(c('American Indian or Alaska Native', 'american indian or alaska native'),
                                           c('Asian or Pacific Islander', 'asian or pacific islander'),
                                           c('Black or African American', 'black'),
                                           c('White', 'white'),
                                           c('More than one race', NA)))
register.ontology.mapping('wonder.to.census.race.3',
                          from.dimensions = 'race',
                          to.dimensions = 'race',
                          mappings = rbind(c('American Indian or Alaska Native', 'american indian or alaska native'),
                                           c('Asian or Pacific Islander', 'asian or pacific islander'),
                                           c('Black or African American', 'black'),
                                           c('White', 'white'),
                                           c('More than one race', NA),
                                           c('Not Reported', NA),
                                           c('Unknown or Not Stated', NA),
                                           c('Not Available', NA)))
register.ontology.mapping('wonder.to.census.ethnicity.1',
                          from.dimensions = 'ethnicity',
                          to.dimensions = 'ethnicity',
                          mappings = rbind(c('Hispanic or Latino', 'hispanic'),
                                           c('Not Hispanic or Latino', 'not hispanic'),
                                           c('Unknown or Not Stated', NA),
                                           c('Not Stated', NA)))
register.ontology.mapping('wonder.to.census.ethnicity.2',
                          from.dimensions = 'ethnicity',
                          to.dimensions = 'ethnicity',
                          mappings = rbind(c('Hispanic or Latino', 'hispanic'),
                                           c('Not Hispanic or Latino', 'not hispanic')))
register.ontology.mapping('census.to.jheem.race',
                          from.dimensions = c('race', 'ethnicity'),
                          to.dimensions = 'race',
                          mappings = rbind(c('white', 'hispanic', 'hispanic'),
                                           c('white', 'not hispanic', 'other'),
                                           c('black', 'hispanic', 'hispanic'),
                                           c('black', 'not hispanic', 'black'),
                                           c('american indian or alaska native', 'hispanic', 'hispanic'),
                                           c('american indian or alaska native', 'not hispanic', 'other'),
                                           c('asian or pacific islander', 'hispanic', 'hispanic'),
                                           c('asian or pacific islander', 'not hispanic', 'other')))
register.ontology.mapping('wonder.to.jheem.race',
                          from.dimensions = c('race', 'ethnicity'),
                          to.dimensions = 'race',
                          mappings = rbind(c('White', 'Hispanic or Latino', 'hispanic'),
                                           c('White', 'Not Hispanic or Latino', 'other'),
                                           c('Black or African American', 'Hispanic or Latino', 'hispanic'),
                                           c('Black or African American', 'Not Hispanic or Latino', 'black'),
                                           c('American Indian or Alaska Native', 'Hispanic or Latino', 'hispanic'),
                                           c('American Indian or Alaska Native', 'Not Hispanic or Latino', 'other'),
                                           c('Asian or Pacific Islander', 'Hispanic or Latino', 'hispanic'),
                                           c('Asian or Pacific Islander', 'Not Hispanic or Latino', 'other'),
                                           c('More than one race','Hispanic or Latino','hispanic'),
                                           c('More than one race','Not Hispanic or Latino','other')))
register.ontology.mapping('wonder.to.jheem.race.2',
                          from.dimensions = c('race'),
                          to.dimensions = 'race',
                          mappings = rbind(c('American Indian/Alaska Native', 'other'),
                                           c('Asian', 'other'),
                                           c('Black', 'black'),
                                           c('Hispanic', 'hispanic'),
                                           c('White', 'other'),
                                           c('Unknown', 'other')))
register.ontology.mapping('jheem.to.cdc.sex',
                          from.dimensions = 'sex',
                          to.dimensions = 'sex',
                          mappings = rbind(c('heterosexual_male', 'male'),
                                           c('msm', 'male'),
                                           c('female', 'female')))
register.ontology.mapping('census.immigration.to.jheem.race',
                          from.dimensions = 'race',
                          to.dimensions = 'race',
                          mappings = rbind(c('Hispanic or Latino', 'hispanic'),
                                           c('White, Non-Hispanic', 'white'),
                                           c('Black', 'black'),
                                           c('Other', 'other'))) # needed?
register.ontology.mapping('emory.sex.to.cdc.sex.temporary',
                          from.dimensions = 'sex',
                          to.dimensions = 'sex',
                          mappings = rbind(c('male', 'male'),
                                           c(NA, 'female')))
register.ontology.mapping('proportion.tested.to.adult.population',
                          from.dimensions = c('race', 'ethnicity'),
                          to.dimensions = 'race',
                          mappings = rbind(c('American Indian or Alaska Native', 'Hispanic or Latino', 'Hispanic'),
                                           c('American Indian or Alaska Native', 'Not Hispanic or Latino', 'American Indian/Alaska Native'),
                                           c('Asian or Pacific Islander', 'Hispanic or Latino', 'Hispanic'),
                                           c('Asian or Pacific Islander', 'Not Hispanic or Latino', 'Asian'),
                                           c('Black or African American', 'Hispanic or Latino', 'Hispanic'),
                                           c('Black or African American', 'Not Hispanic or Latino', 'Black'),
                                           c('More than one race', 'Hispanic or Latino', 'Hispanic'),
                                           c('More than one race', 'Not Hispanic or Latino', 'Multiracial'),
                                           c('White','Hispanic or Latino','Hispanic'),
                                           c('White','Not Hispanic or Latino','White')))
register.ontology.mapping('proportion.tested.to.adult.population.2',
                          from.dimensions = c('race', 'ethnicity'),
                          to.dimensions = 'race',
                          mappings = rbind(c('American Indian/Alaska Native', 'American Indian or Alaska Native', 'Not Hispanic or Latino'),
                                           c('Asian', 'Asian', 'Not Hispanic or Latino'),
                                           c('Black', 'Black or African American', 'Not Hispanic or Latino'),
                                           c('Hispanic', 'More than one race', 'Hispanic or Latino'),
                                           c('Multiracial', 'More than one race', 'Not Hispanic or Latino'),
                                           c('Native Hawaiian/Other Pacific Islander', 'Asian or Pacific Islander', 'Not Hispanic or Latino'),
                                           c('Other race', 'More than one race', 'Not Hispanic or Latino'),
                                           c('White', 'White', 'Not Hispanic or Latino')))
